<!-- declare our angular app and controller -->
<div class="container" ng-controller="postController">
    <div class="text-left">
        <input type="text" size="10" name="author" ng-model="author" placeholder="Автор">
        <input type="text" size="50" name="content" ng-model="content" placeholder="Сообщение">
        <button ng-click="sendPost()" class="btn btn-primary btn-lg">
            <i class="glyphicon glyphicon-plus-sign"></i> Написать сообщение
        </button>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">
                Лента постов
            </h1>
            <button ng-click="all()" class="btn btn-primary btn-lg">
                <i class="glyphicon glyphicon-sort-by-attributes"></i>
            </button>
            <button ng-click="latest()" class="btn btn-primary btn-lg">
                <i class="glyphicon glyphicon-sort-by-attributes-alt"></i>
            </button>
            <button ng-click="random()" class="btn btn-primary btn-lg">
                <i class="glyphicon glyphicon-random"></i>
            </button>

            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Дата</th>
                    <th>Сообщение</th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="post in posts">
                    <td class="nowrap" post-date="post.postedAt">
                    </td>
                    <td>
                        {{ post.author  }}: {{ post.content  }}
                    </td>
                </tr>
                </tbody></table>
        </div>
    </div>
</div>